name: Deploy React App
on: push
jobs:
  jobLint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Lint application
        run: npm run lint
  jobDeploy:
    runs-on: ubuntu-latest
    needs: jobLint
    steps:
      - name: Get code from repository
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying ...
