name: Build and Upload
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist
          # путь к нужным нам файлам в нашей директории проекта
          name: dist-files
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build project
        uses: actions/download-artifact@v3
        # action, который позволит скачать файлы
        with:
          name: dist-files
